### ISSUE TITLE
Kyma-cli package failing to build

### ISSUE THREAD

**Issue by dgalbraith** [dgalbraith/chocolatey-packages#382] opened 2022-03-03 22:41 UTC
The kyma-cli package is failing to build with an `Invalid version` error:

![image](https://user-images.githubusercontent.com/1270002/156664994-f730510d-74e2-4307-9b99-a119c17515a1.png)

**Comment by dennis-ge** [comment] 2022-06-07 10:14
Hey @dgalbraith, the kyma-cli installation on choco is outdated. The latest version is [2.2.0](https://github.com/kyma-project/cli/releases/tag/2.2.0), but on the choco website the latest version is [2.0.4](https://community.chocolatey.org/packages/kyma-cli). I see that this was a problem previously and it got fixed in https://github.com/dgalbraith/chocolatey-packages/issues/364 but it somehow is still present. Do you know what the cause may be?

Can also assist if you need any help/have any questions :)

**Closed** 2022-07-06 23:47 UTC
